# Generated by Django 4.0.2 on 2022-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='higher',
            name='uni_finish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Finishing Date'),
        ),
        migrations.AlterField(
            model_name='higher',
            name='uni_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Starting Date'),
        ),
    ]
