# Generated by Django 4.0.2 on 2022-03-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='id',
        ),
        migrations.AddField(
            model_name='state',
            name='state_pk',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='State User ID'),
            preserve_default=False,
        ),
    ]
